spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
#      httpclient:
#        connect-timeout: 1000
#        response-timeout: 2s

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank GateWay Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10  # Circuit Breaker will keep track of the outcome (success or failure) of the last 10 requests
      permittedNumberOfCallsInHalfOpenState: 2 # allow 2 request in the half-open status, based on this 2 requests,
      #go to the either close or open
      failureRateThreshold: 10 # about what percentage of those observed requests need to be failures before the
      #Circuit Breaker trips and opens.
      waitDurationInOpenState: 5000 # wait 5 secs before going to half-open and allow partial traffic